### ISSUE TITLE
Warning: SocketClustered: `ref` is not a prop. 

### ISSUE THREAD

**Issue by rogchap** [mattkrick/redux-socket-cluster#3]
Getting two warning messages when using redux-socket-cluster:

`Warning: SocketClustered: `ref` is not a prop.`
`Warning: SocketClustered: `key` is not a prop.`

![image](https://cloud.githubusercontent.com/assets/270252/15166595/b6739f88-1763-11e6-8ddb-e5021c8d7188.png)

Related to https://github.com/facebook/react/issues/2429

These warnings also appear on the **Meatier** repo. 
Not sure where this error/warning is coming from

**Comment by mattkrick** [comment]
thanks for pointing this out...but the root cause is in react. See https://github.com/facebook/react/pull/6268
