### ISSUE TITLE
socketclient.setAuthToken

### ISSUE THREAD

**Issue by cometta** [mattkrick/redux-socket-cluster#5]
I use reduxSocket({}, reduxSocketOptions)   on appContainer (main container) instead of specify page because i want the entire app to use Websocket. Once app is loaded, user is able to use websocket without authentication. Later, when user clicks to authenticate him/her self. How to socketClient.setAuthToken Or use AuthEngine to call "loadToken" ? Reason because AuthEngine only called once when the app is loaded in this case.

**Comment by mattkrick** [comment]
does the JWT come from your server or a 3rd party service? If you control the JWT creation, I'd probably handle authentication on the server to make it easier. If not, then whenever you receive your JWT, call call `socket.authenticate(JWT, cb)`. redux-socket-cluster doesn't really handle that, it just keeps the useful bits of state in your redux store.
